import { site } from '@/lib/site';
import type { SchemaNode } from '@/lib/schema';
import { findLawyer, lawyers } from '@/lib/lawyers';
export function JsonLd({nodes}:{nodes:SchemaNode[]}){return <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({'@context':'https://schema.org','@graph':nodes}).replace(/</g,'\\u003c')}}/>}
export function Breadcrumb({items}:{items:{name:string;path:string}[]}){return <nav aria-label="面包屑" className="breadcrumbs"><a href="/">首页</a>{items.map((i,n)=><span key={i.path}><span aria-hidden="true">/</span>{n===items.length-1?<span aria-current="page">{i.name}</span>:<a href={i.path}>{i.name}</a>}</span>)}</nav>}
export function PageIntro({eyebrow,title,description,items}:{eyebrow:string;title:string;description:string;items:{name:string;path:string}[]}){return <section className="page-intro"><div className="wrap"><Breadcrumb items={items}/><div className="eyebrow">{eyebrow}</div><h1 className="serif">{title}</h1><p>{description}</p></div></section>}
export function LawyerCards({ids}:{ids?:string[]}){const list=ids?ids.map(findLawyer).filter((l):l is typeof lawyers[number]=>!!l):lawyers;return <div className="lawyer-grid">{list.map(l=><article className="lawyer-card" key={l.id}><a href={'/lawyers/'+l.id+'/'} className="lawyer-card-main"><div className="portrait-frame"><img src={l.image} alt={`${l.name}律师`} width="140" height="180" loading="lazy"/></div><div><p className="lawyer-role">{l.role}</p><h3 className="serif">{l.name}<span>律师</span></h3><p className="lawyer-tagline">{l.tagline}</p></div></a><div className="tags">{l.tags.map(t=><span key={t}>{t}</span>)}</div><a className="text-link" href={'/lawyers/'+l.id+'/'}>了解律师背景与业务 <span>→</span></a></article>)}</div>}
export function ContactBand(){return <section className="contact-band"><div className="wrap contact-band-inner"><div><div className="eyebrow">LET’S TALK</div><h2 className="serif">把问题说清楚，从一次沟通开始。</h2><p>先梳理事实、争议与现有材料，再讨论适合您的下一步。</p></div><div className="band-contact"><a className="band-phone" href={site.phoneHref}>{site.phone}</a><p>电话 / 微信同号 · {site.contactLabel}</p><a className="text-link" href="/contact/">咨询与到所准备 ↗</a></div></div></section>}
export function Sidebar({sections,serviceName}:{sections:{id:string;title:string}[];serviceName?:string}){return <aside className="content-sidebar"><div className="side-box"><div className="eyebrow">ON THIS PAGE</div><nav aria-label="本页目录">{sections.map(s=><a key={s.id} href={'#'+s.id}>{s.title}<span>↓</span></a>)}</nav></div><div className="side-contact"><p className="eyebrow">上海 · 杨浦</p><h3>咨询接待{serviceName?'这一问题':''}</h3><a className="phone" href={site.phoneHref}>{site.phone}</a><p>微信同号 · {site.contactLabel}<br/>{site.hours}</p><a className="text-link" href="/contact/">咨询准备与到所方式 →</a></div></aside>}
