import { notFound } from 'next/navigation';
import { lawyers,findLawyer } from '@/lib/lawyers';
import { findService } from '@/lib/services';
import { pageMeta,site } from '@/lib/site';
import { Breadcrumb,JsonLd,ContactBand,Sidebar } from '@/components/site-shared';
import { breadcrumbSchema,personSchema,webpageSchema } from '@/lib/schema';
import { publishedArticles } from '@/lib/articles';
type Props={params:Promise<{slug:string}>};
export const generateStaticParams=()=>lawyers.map(l=>({slug:l.id}));
export async function generateMetadata({params}:Props){const l=findLawyer((await params).slug);return l?pageMeta(l.name+'律师｜'+l.role,l.intro,'/lawyers/'+l.id+'/'):{};}
export default async function LawyerPage({params}:Props){const l=findLawyer((await params).slug);if(!l)notFound();const path='/lawyers/'+l.id+'/';const crumbs=[{name:'律师团队',path:'/lawyers/'},{name:l.name+'律师',path}];const articles=publishedArticles.filter(a=>a.authorId===l.id);return <main id="main"><JsonLd nodes={[personSchema(l),{...webpageSchema(path,l.name+'律师',l.intro,'ProfilePage'),mainEntity:{'@id':personSchema(l)['@id']}},breadcrumbSchema(crumbs)]}/><section className="profile-hero"><div className="wrap"><Breadcrumb items={crumbs}/><div className="profile-top"><img className="profile-photo" src={l.image} alt={l.name+'律师肖像'} width="180" height="250"/><div><div className="eyebrow">{l.role}</div><h1 className="serif">{l.name}<span>律师</span></h1><p>{l.tagline}</p><div className="tags">{l.tags.map(t=><span key={t}>{t}</span>)}</div></div></div></div></section><section className="section"><div className="wrap content-layout"><div className="reading"><section id="background"><h2>律师介绍</h2><p>{l.intro}</p>{l.paragraphs.map(p=><p key={p}>{p}</p>)}</section><section id="experience"><h2>教育与工作经历</h2><p style={{marginBottom:25}}>{l.education}</p><dl className="timeline">{l.milestones.map(([year,event])=><div key={year}><dt>{year}</dt><dd>{event}</dd></div>)}</dl></section><section id="practice"><h2>业务中的关注重点</h2><div className="focus-list">{l.practices.map(p=><div key={p.title}><h3>{p.title}</h3><p>{p.text}</p></div>)}</div><p className="note">以上为本所提供的业务经历概述，不构成对个案结果的承诺。</p></section><section id="services"><h2>相关服务方向</h2><div className="related-services">{l.services.map(findService).filter(Boolean).map(s=><a href={'/services/'+s!.slug+'/'} key={s!.slug}>{s!.title} →</a>)}</div></section>{articles.length>0?<section id="articles"><h2>署名文章</h2><div className="article-list">{articles.map(a=><a className="article-row" key={a.slug} href={'/insights/'+a.slug+'/'}><h3>{a.title}</h3><p>{a.summary}</p></a>)}</div></section>:null}<section id="identity"><h2>执业信息核验</h2><p>所属机构：上海江怀律师事务所。律师履历依据本所提供的介绍整理，核验执业信息时请同时比对姓名与所属机构。</p><a className="registry-link" href={site.registry} target="_blank" rel="noopener noreferrer">上海市司法局 · 律师查询服务 ↗</a><p className="note">资料整理日期：{site.updated}。</p></section></div><Sidebar sections={[{id:'background',title:'律师介绍'},{id:'experience',title:'教育与工作经历'},{id:'practice',title:'业务关注重点'},{id:'services',title:'相关服务'},{id:'identity',title:'执业信息核验'}]}/></div></section><ContactBand/></main>}
