import { notFound } from 'next/navigation';
import { services,findService } from '@/lib/services';
import { pageMeta,sources,site } from '@/lib/site';
import { JsonLd,PageIntro,LawyerCards,ContactBand,Sidebar } from '@/components/site-shared';
import { breadcrumbSchema,webpageSchema,serviceSchema } from '@/lib/schema';
type Props={params:Promise<{slug:string}>};
export const generateStaticParams=()=>services.map(s=>({slug:s.slug}));
export async function generateMetadata({params}:Props){const s=findService((await params).slug);return s?pageMeta('上海'+s.title+'法律服务',s.intro,'/services/'+s.slug+'/'):{};}
export default async function ServicePage({params}:Props){const s=findService((await params).slug);if(!s)notFound();const path='/services/'+s.slug+'/';const crumbs=[{name:'业务领域',path:'/services/'},{name:s.title,path}];const refs=s.sources.map(id=>sources.find(s=>s.id===id)).filter(Boolean);return <main id="main"><JsonLd nodes={[{...webpageSchema(path,s.title,s.intro),mainEntity:{'@id':serviceSchema(s)['@id']},citation:refs.map(r=>r!.url)},serviceSchema(s),breadcrumbSchema(crumbs)]}/><PageIntro eyebrow={s.english} title={s.title} description={s.intro} items={crumbs}/><section className="section"><div className="wrap content-layout"><div className="reading"><section id="situations"><h2>哪些情况可以先与律师沟通</h2><ul>{s.scenarios.map(x=><li key={x}>{x}</li>)}</ul></section><section id="approach"><h2>我们会怎样梳理问题</h2><div className="focus-list">{s.focus.map((f,i)=><div className="numbered-item" key={f.title}><span>0{i+1}</span><div><h3>{f.title}</h3><p>{f.text}</p></div></div>)}</div></section><section id="prepare"><h2>第一次咨询，可以准备这些材料</h2><ul className="material-list">{s.materials.map(m=><li key={m}>{m}</li>)}</ul><p className="note">初次联系可先说明概括情况。身份证号、银行账号、儿童个人信息等敏感内容，请在与律师确认传递方式后再提供。</p><a className="text-link" href="/resources/consultation/">使用咨询准备清单 →</a></section><section id="questions"><h2>咨询前常见问题</h2>{s.faq.map(f=><div className="faq-item" key={f.q}><h3>{f.q}</h3><p>{f.a}</p></div>)}</section><section id="references"><h2>相关法律依据与阅读入口</h2><div className="source-list">{refs.map(r=><a href={r!.url} key={r!.id} target="_blank" rel="noopener noreferrer">{r!.name} · {r!.issuer} ↗</a>)}</div><p className="note">本页为服务范围及咨询准备介绍，不代替个案法律意见。法规适用需结合事实、时间及现行规则。内容整理日期：{site.updated}。</p></section><section><h2>相关业务</h2><div className="related-services">{s.related.map(id=>findService(id)).filter(Boolean).map(r=><a href={'/services/'+r!.slug+'/'} key={r!.slug}>{r!.title} →</a>)}</div></section></div><Sidebar serviceName={s.title} sections={[{id:'situations',title:'适用场景'},{id:'approach',title:'问题梳理'},{id:'prepare',title:'材料准备'},{id:'questions',title:'常见问题'},{id:'references',title:'法律依据'}]}/></div></section><section className="section section-muted"><div className="wrap"><div className="section-head"><div><div className="eyebrow">OUR LAWYERS</div><h2 className="serif">相关业务律师</h2></div><p>了解律师的背景与业务方向，具体委托由双方沟通确认。</p></div><LawyerCards ids={s.lawyers}/></div></section><ContactBand/></main>}
