import {notFound} from 'next/navigation';
import {publishedArticles,articleSchemas} from '@/lib/articles';
import {findLawyer} from '@/lib/lawyers';
import {findService} from '@/lib/services';
import {pageMeta} from '@/lib/site';
import {PageIntro,ContactBand,JsonLd,Sidebar} from '@/components/site-shared';
import {breadcrumbSchema} from '@/lib/schema';
type Props={params:Promise<{slug:string}>};
export const generateStaticParams=()=>publishedArticles.map(a=>({slug:a.slug}));
export async function generateMetadata({params}:Props){const {slug}=await params;const a=publishedArticles.find(a=>a.slug===slug);return a?pageMeta(a.title,a.summary,'/insights/'+a.slug+'/'):{};}
export default async function ArticlePage({params}:Props){const {slug}=await params;const a=publishedArticles.find(a=>a.slug===slug);if(!a)notFound();const crumbs=[{name:'家事指南',path:'/insights/'},{name:a.title,path:'/insights/'+a.slug+'/'}];const author=findLawyer(a.authorId)!;const reviewer=findLawyer(a.reviewerId)!;return <main id="main"><JsonLd nodes={[...articleSchemas(a),breadcrumbSchema(crumbs)]}/><PageIntro eyebrow="JIANGHUAI INSIGHTS" title={a.title} description={a.summary} items={crumbs}/><section className="section"><div className="wrap content-layout"><article className="reading"><div className="article-meta"><a rel="author" href={'/lawyers/'+author.id+'/'}>作者：{author.name}律师</a><a href={'/lawyers/'+reviewer.id+'/'}>复核：{reviewer.name}律师</a><span>发布：<time dateTime={a.datePublished}>{a.datePublished}</time></span><span>更新：<time dateTime={a.dateModified}>{a.dateModified}</time></span><span>复核：<time dateTime={a.lastReviewed}>{a.lastReviewed}</time></span></div><p className="note">适用范围：{a.jurisdiction}</p>{a.sections.map(s=><section id={s.id} key={s.id}><h2>{s.title}</h2>{s.paragraphs.map((p,i)=><p key={i}>{p}</p>)}{s.bullets?<ul>{s.bullets.map(b=><li key={b}>{b}</li>)}</ul>:null}</section>)}{a.faqs.length>0?<section><h2>相关问题</h2>{a.faqs.map(f=><div className="faq-item" key={f.q}><h3>{f.q}</h3><p>{f.a}</p></div>)}</section>:null}<section><h2>法源与参考资料</h2><div className="source-list">{a.sourceUrls.map(s=><a key={s.url} href={s.url} target="_blank" rel="noopener noreferrer">{s.name} ↗</a>)}</div><p className="note">本文为一般法律信息，不能代替对具体案件材料的审查；个案结果取决于事实、证据与适用法律。</p><a className="text-link" href={'/services/'+a.serviceSlug+'/'}>{findService(a.serviceSlug)!.title}服务 →</a></section></article><Sidebar sections={a.sections.map(s=>({id:s.id,title:s.title}))}/></div></section><ContactBand/></main>}
